### PR TITLE
Publish v3.7.3

### PR DESCRIPTION
**Pull request by daileytj**
#### Changes proposed in this Pull Request:
- Prepare to publish v3.7.3

### CODE REVIEW

**Comment by jeffvg** [comment]
Leaving this here from previous conversation with Tom. On my local I see these errors and bob build loops for longer than expected deploying to Android. This is the terminal output...

image
image


After adjusting shared-auth to use the same version of typescript as the package/project example the project deploys but with different errors...

image

**Review by emclaug2 — APPROVED** [review]

**Comment by jeffvg** [comment]
are we able to clean these up in shared-auth? Everything is working as intended but terminal output just ugly.

image
image
image
image

**Comment by daileytj** [comment]
@jeffvg I don't have a fix for these ¯\_(ツ)_/¯

**Comment by emclaug2** [comment]
> @jeffvg I don't have a fix for these ¯_(ツ)_/¯

I've seen the same thing, but if I'm remembering correctly we've had this issue for a while now.  I'll approve this.

**Review by emclaug2 — APPROVED** [review]

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
