### PR TITLE
Feature/blui 2778 add username regex and translations

### PR DESCRIPTION
**Pull request by daileytj**
Fixes Fixes #112 /BLUI-2778.

#### Changes proposed in this Pull Request:
- Add username regex and translations

#### To Test:
- To be tested as part of https://github.com/brightlayer-ui/react-native-workflows/pull/168

### CODE REVIEW

**Comment by jeffvg** [comment]
looks good

image

**Comment by jeffvg** [comment]
was the change password screen part of this for the title when you did translations for PT?

image

**Comment by daileytj** [comment]
> was the change password screen part of this for the title when you did translations for PT?
> 
> image

The translations were already there, we just needed to actually do the translation. I believe I fixed this in the Portuguese PR. I may or may not have merged that into the current workflow PR

**Comment by jeffvg** [comment]
> 

guess it didn't make it in to https://github.com/brightlayer-ui/react-native-workflows/pull/166 becuase we didn't know at the time the shared auth was going to be updated....

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
